---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/StringConcatenation:
  Exclude:
  - lib/aranha/parsers/html/node/default/string_support.rb
  - lib/aranha/parsers/rspec/source_target_fixtures_controller.rb
  - lib/aranha/parsers/source_address/file.rb
  - lib/aranha/parsers/source_address.rb
