---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
RSpec/FilePath:
  Exclude:
  - spec/lib/aranha/parsers/source_address/detect_sub_spec.rb
RSpec/SpecFilePathFormat:
  Exclude:
  - spec/lib/aranha/parsers/source_address/detect_sub_spec.rb
Rails/FilePath:
  Exclude:
  - lib/aranha/parsers/base.rb
Style/FileRead:
  Exclude:
  - lib/aranha/parsers/source_address/file.rb
Style/FileWrite:
  Exclude:
  - lib/aranha/parsers/base.rb
Style/MapToHash:
  Exclude:
  - lib/aranha/parsers/html/node/base.rb
Style/OptionalBooleanParameter:
  Exclude:
  - lib/aranha/parsers/html/node/default/string_support.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - aranha-parsers.gemspec
  - lib/aranha/parsers/patches/ofx_parser.rb
  - lib/aranha/parsers/rspec/shared_examples/source_target_fixtures.rb
  - spec/lib/aranha/parsers/rspec/shared_examples/source_target_fixtures_spec.rb
  - spec/lib/aranha/parsers/source_address/detect_sub_spec.rb
  - spec/lib/aranha/parsers/source_address/http_get_spec.rb
  - spec/lib/aranha/parsers/source_address_spec.rb
  - spec/lib/aranha/parsers/source_target_fixtures_spec.rb
  - spec/lib/rubocop_check_spec.rb
  - spec/spec_helper.rb
Style/RedundantRegexpEscape:
  Exclude:
  - lib/aranha/parsers/html/node/default/string_support.rb
Style/StringConcatenation:
  Exclude:
  - lib/aranha/parsers/html/node/default/string_support.rb
  - lib/aranha/parsers/rspec/source_target_fixtures_controller.rb
  - lib/aranha/parsers/source_address/file.rb
  - lib/aranha/parsers/source_address.rb
